name: Test

on:
  push:
    paths:
      - '**.go'
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.7
          - 1.8
          - 1.9
          - 1.10
          - 1.11
          - 1.12
          - 1.13
          - 1.17
          - 1.18
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - run: |
          go test -v -covermode=count -coverprofile=coverage.out
          go vet ./...
          test -z "$(gofmt -d -s . | tee /dev/stderr)"

      - if: github.ref == 'refs/heads/master'
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get github.com/mattn/goveralls
          goveralls -coverprofile=coverage.out -service=github
